version: '3.7'
services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cargo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Three.ru2015

  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
# version: "3.9"

# services:
#   web:
#     build: .
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#     volumes:
#       - .:/app
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_DB=your_db_name
#       - POSTGRES_USER=your_username
#       - POSTGRES_PASSWORD=your_password